---
# tasks file for ansible-role-smartd

# DELL:
# smartctl --scan outputs this, which one can't add to smartd.conf:
# /dev/sda -d scsi # /dev/sda, SCSI device

# With smartmontools 6.4 one can just use the standard DEVICESCAN line
# With smartmontools 6.2 we do this instead >

- name: move the default smartd.conf
  command: mv -v {{ smartd_config_file }} {{ smartd_config_file }}.bkp creates={{ smartd_config_file }}.bkp

- name: grab list of devices
  command: "smartctl --scan"
  register: smart_list_of_devices
  always_run: True

- debug: var=item.split('#').0
  with_items: smart_list_of_devices.stdout_lines

- name: DELL - populate smartd file with these devices except /dev/sda
  lineinfile: dest={{ smartd_config_file }} regexp='{{ item.split('#').0 }}{{ smartd_device_arguments }}$' line="{{ item.split('#').0 }}{{ smartd_device_arguments }}" state=present create=yes
  with_items: smart_list_of_devices.stdout_lines
  when: "'/dev/sd' not in item"
  notify:
    - restart smartd
