---
# tasks file for ansible-role-smartd

# DELL:
# smartctl --scan outputs this, which one can't add to smartd.conf:
# /dev/sda -d scsi # /dev/sda, SCSI device

# With smartmontools 6.4 one can just use the standard DEVICESCAN line
# With smartmontools 6.2 we do this instead >

- name: template in almost empty smartd.conf
  template: src=smartd.conf.j2 dest={{ smartd_config_file }} backup=yes mode=0644

- name: grab list of devices
  command: "smartctl --scan"
  register: smart_list_of_devices
  always_run: True

- debug: var=item.split('#').0
  with_items: smart_list_of_devices.stdout_lines

- name: DELL - populate smartd file with these devices
  lineinfile: dest={{ smartd_config_file }} regexp='{{ item.split('#').0 }} {{smartd_device_arguments }}$' line="{{ item.split('#').0 }} {{ smartd_device_arguments }}" state=present
  with_items: smart_list_of_devices.stdout_lines
  when: "'/dev/sda' not in item"
