---
# tasks file for ansible-role-smartd

- debug: var=ansible_devices.sda.vendor

- name: grab list of devices
  command: "smartctl --scan"
  register: smart_list_of_devices
  always_run: True

- debug: var=smart_list_of_devices

- name: template in almost empty smartd.conf
  template: src=smartd.conf.j2 dest={{ smartd_config_file }} backup=yes mode=0644

## Populate smartd.conf
- include: dell.yml
  when: ansible_devices.sda.vendor == "DELL"

- include: generic.yml
  when: ansible_devices.sda.vendor != "DELL"
##

- name: enable smartd service
  service: name=smartd enabled=yes
