---
# tasks file for ansible-role-smartd

# DELL:
# smartctl --scan outputs this, which one can't add to smartd.conf:
# /dev/sda -d scsi # /dev/sda, SCSI device


- debug: var=ansible_devices.sda.vendor

- name: grab list of devices
  command: "smartctl --scan"
  register: smart_list_of_devices
  always_run: True

- debug: var=smart_list_of_devices

- name: populate smartd file with these devices
  lineinfile: dest={{ smartd_config_file }} regexp='{{ item }}$' line="{{ item }}" state=present
  with_items: smart_list_of_devices.stdout_lines
  when: "'/dev/sda' not in item" and ansible_devices.sda.vendor == "DELL"

# Comment out devicescan line

- name: enable smartd service
  service: name=smartd enabled=yes
