---
# tasks file for ansible-role-smartd
# If DELL = do some workaround
# If smartd_monitor_all_found_disks is True - add all from smartctl --scan
# If smartd_monitor_all_found_disks is False - use the smartd.conf from the package and its DEVICESCAN

- debug: var=ansible_devices.sda.vendor

## Populate smartd.conf
- include: dell.yml
  when: ansible_devices.sda.vendor == "DELL"

- include: generic.yml
  when: smartd_monitor_all_found_disks
##

- name: enable smartd service
  service: name=smartd enabled=yes
