---
# tasks file for ansible-role-smartd
# If DELL = do some workaround
# If smartd_monitor_all_found_disks is True - add all from smartctl --scan
# If smartd_monitor_all_found_disks is False - use the smartd.conf from the package and its DEVICESCAN

- debug: var=ansible_devices.sda.vendor
  when: ansible_devices.sda is defined

- name: grab list of devices by running smartctl --scan
  command: "/usr/sbin/smartctl --scan"
  register: smart_list_of_devices
  always_run: True

## Populate smartd.conf
- include: dell.yml
  when: ansible_devices.sda is defined and ansible_devices.sda.vendor == "DELL"

- include: generic.yml
  when: smartd_monitor_all_found_disks
##

- name: enable smartd service
  service: name=smartd enabled={{ smartd_service_enabled }} state={{ smartd_service_state }}
